In [ ]:
from keras.preprocessing.image import load_img, img_to_array, ImageDataGenerator
from keras.applications.vgg16 import preprocess_input

#load the image
my_image = load_img('COVID-76.png', target_size=(224, 224))

#preprocess the image
my_image = img_to_array(my_image)
my_image = my_image.reshape((1, my_image.shape[0], my_image.shape[1], my_image.shape[2]))
my_image = preprocess_input(my_image)

#make the prediction
prediction = model.predict(my_image)

## Manual Testing Using VGG Network

In [1]:
import os
from keras.preprocessing.image import load_img, img_to_array, ImageDataGenerator
from keras.applications.vgg16 import preprocess_input

Using TensorFlow backend.


In [3]:
from tensorflow.keras.models import load_model
model = load_model('Chest_Xray_withVGG_v2.h5')

In [7]:
import numpy as np

In [18]:
dirt = 'COVID-19_Radiography_Dataset/Normal'

for i in os.listdir(dirt):
    pd = []
    #load the image
    my_image = load_img(os.path.join(dirt, i), target_size=(224, 224))
    
    #preprocess the image
    my_image = img_to_array(my_image)
    #my_image = my_image/255.0 
    my_image = my_image.reshape((1, my_image.shape[0], my_image.shape[1], my_image.shape[2]))
    
    my_image = preprocess_input(my_image)
    
    #make the prediction
    prediction = model.predict(my_image)
    prediction = np.around(prediction, decimals=3)
    print(prediction)

[[0.034 0.501 0.464 0.   ]]
[[0.033 0.513 0.454 0.   ]]
[[0.034 0.508 0.458 0.   ]]
[[0.034 0.517 0.449 0.   ]]
[[0.037 0.507 0.456 0.   ]]
[[0.034 0.503 0.463 0.   ]]
[[0.032 0.517 0.45  0.   ]]
[[0.032 0.49  0.478 0.   ]]
[[0.032 0.508 0.46  0.   ]]
[[0.033 0.521 0.446 0.   ]]
[[0.033 0.52  0.447 0.   ]]
[[0.035 0.518 0.447 0.   ]]
[[0.034 0.505 0.46  0.   ]]
[[0.043 0.505 0.452 0.   ]]
[[0.033 0.521 0.446 0.   ]]
[[0.033 0.517 0.45  0.   ]]
[[0.032 0.531 0.437 0.   ]]
[[0.036 0.499 0.465 0.   ]]
[[0.036 0.52  0.444 0.   ]]
[[0.035 0.514 0.451 0.   ]]
[[0.036 0.518 0.446 0.   ]]
[[0.033 0.519 0.448 0.   ]]
[[0.038 0.519 0.443 0.   ]]
[[0.032 0.516 0.452 0.   ]]
[[0.033 0.508 0.459 0.   ]]
[[0.034 0.522 0.444 0.   ]]
[[0.032 0.473 0.494 0.   ]]
[[0.034 0.53  0.436 0.   ]]
[[0.033 0.52  0.447 0.   ]]


KeyboardInterrupt: 

# Manual Testing Using the Efficient Network

In [19]:
pip install efficientnet

You should consider upgrading via the 'c:\users\susant\appdata\local\programs\python\python37\python.exe -m pip install --upgrade pip' command.


In [2]:
import os
#import tensorflow 
from keras.preprocessing.image import load_img, img_to_array, ImageDataGenerator
from tensorflow.keras.applications.efficientnet import preprocess_input
from efficientnet.tfkeras import EfficientNetB4

In [3]:
from tensorflow.keras.models import load_model
model = load_model('Chest_Xray_Ef.h5')

OSError: SavedModel file does not exist at: Chest_Xray_Ef.h5/{saved_model.pbtxt|saved_model.pb}

In [33]:
dirt = 'COVID-19_Radiography_Dataset/Viral Pneumonia'

for i in os.listdir(dirt):
    pd = []
    #load the image
    my_image = load_img(os.path.join(dirt, i), target_size=(224, 224))
    
    #preprocess the image
    my_image = img_to_array(my_image)
    my_image = my_image/255.0 
    my_image = my_image.reshape((1, my_image.shape[0], my_image.shape[1], my_image.shape[2]))
    
    my_image = preprocess_input(my_image)
    
    #make the prediction
    prediction = model.predict(my_image)
    prediction = np.around(prediction, decimals=3)
    print(prediction)

[[0.    0.    0.001 0.999]]
[[0.    0.    0.003 0.997]]
[[0. 0. 0. 1.]]
[[0.    0.001 0.231 0.768]]
[[0.    0.    0.006 0.993]]
[[0.003 0.041 0.819 0.138]]
[[0.002 0.002 0.636 0.36 ]]
[[0.    0.    0.    0.999]]
[[0.    0.001 0.002 0.997]]
[[0.    0.001 0.001 0.997]]
[[0.04  0.011 0.013 0.936]]
[[0.101 0.071 0.022 0.806]]
[[0.001 0.006 0.388 0.605]]
[[0.    0.    0.002 0.998]]
[[0.008 0.206 0.208 0.578]]
[[0.    0.    0.    0.999]]
[[0.045 0.006 0.091 0.859]]
[[0.002 0.    0.011 0.988]]
[[0.062 0.018 0.003 0.917]]
[[0.001 0.005 0.001 0.993]]
[[0.    0.    0.001 0.999]]
[[0.02  0.002 0.069 0.908]]
[[0.004 0.    0.001 0.995]]
[[0.    0.    0.007 0.992]]
[[0.    0.001 0.026 0.973]]
[[0.076 0.016 0.054 0.854]]
[[0.    0.    0.007 0.992]]
[[0. 0. 0. 1.]]
[[0.    0.002 0.358 0.639]]
[[0. 0. 0. 1.]]
[[0.    0.    0.003 0.997]]
[[0.001 0.002 0.125 0.872]]
[[0.002 0.002 0.017 0.979]]
[[0.    0.001 0.008 0.99 ]]
[[0.    0.    0.001 0.999]]
[[0.    0.001 0.013 0.986]]
[[0.    0.    0.025 0.975]]


KeyboardInterrupt: 